[project]
name = "corpay-cli"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "William Astley", email = "william.astley@algebraicwealth.com"},
]
dependencies = ["pydantic-cli>=9.1.0", "pydantic-settings>=2.11.0", "pydantic-settings-manager>=2.2.0", "typer>=0.19.2", "click>=8.3.0", "python-fire>=0.1.0", "cement>=3.0.14", "cliff>=4.11.0", "docopt>=0.6.2", "argh>=0.31.3", "plac>=1.4.5", "plumbum>=1.9.0", "textual>=6.1.0", "rich>=14.1.0", "urwid>=3.0.3", "py-cui>=0.1.6", "pyTermTk>=0.46.0a0", "picotui>=1.2.1", "npyscreen>=4.10.5", "asciimatics>=1.15.0", "pytermgui>=7.7.4", "InquirerPy>=0.3.4", "questionary>=2.1.1", "PyInquirer>=1.0.0", "prompt-toolkit>=3.0.52", "bullet>=2.2.0", "simple-term-menu>=1.6.6", "pick>=2.4.0", "consolemenu>=1.0.1", "tqdm>=4.67.1", "alive-progress>=3.3.0", "progressbar2>=4.5.0", "halo>=0.0.31", "yaspin>=3.2.0", "enlighten>=1.14.1", "progress>=1.6.1", "colorama>=0.4.6", "termcolor>=3.1.0", "blessed>=1.22.0", "dynaconf>=3.2.11", "omegaconf>=2.3.0", "hydra-core>=1.3.2", "python-decouple>=3.8", "envparse>=0.2.0", "sacred>=0.8.7", "tabulate>=0.9.0", "humanize>=4.13.0", "termtables>=0.2.4", "configpile>=10.1.3", "pydantic[email]>=2.11.9", "pydantic-core>=2.33.2", "pathlib2>=2.3.7.post1", "loguru>=0.7.3", "typer-cli>=0.19.2"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
